### ISSUE TITLE
How to use own data?

### ISSUE THREAD

**Issue by saskra** [LzVv123456/Deep-Reinforced-Tree-Traversal#2]
Thanks for the interesting paper and the source code! Are there also instructions on how I have to format my own data in order to test your method on it?

**Comment by LzVv123456** [comment]
Hello Saskra, 

Thanks for reaching out. 

For the inference purpose, I would suggest first resample the your own CTA image to match the toy example’s spacing. Then you need to provide an initial point that around coronary entry and organize it's location (with respect to image volume, not world) to the
same format of the txt file. 

However, the pre-trained weight we released are also a toy example due to many other policies. So there is chance that is may fail your case. Generally the algorithm will perform better if it is trained on your own data with similar distribution.

Best,
Zhuowei

**Comment by saskra** [comment]
Thank you very much for this very quick answer!

However, I don't have any blood vessel data from the heart, but from other organs. Is there any chance that I could still use this algorithm for that, or would I have to do some major reworking?

**Comment by LzVv123456** [comment]
You can give a try and I don’t know the answer yet. Since the overall environment is quite different even though the model only consume local patches.

However, for some failure cases (over tracing) during our experiments, the algorithms some times traced a large amount of lung vessels (both artery and veins) as well. 
This might be a sign that vessels share the similar features and potentially share one model.

In general, you can not expect a reasonable results. It will make more sense if you use our model as a pre-train and fine-tune on your data.

**Comment by saskra** [comment]
Thank you, I will test this as soon as I find the time. It will probably be more time-consuming because our vessel data also come from modalities other than CTA.
